### ISSUE TITLE
Automatically Add the `created_at` Namespace Property

### ISSUE THREAD

**Issue by srilman** [Bodo-inc/denali#6]
In the OpenAPI spec for REST catalogs (https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml), when creating namespaces, the server is allowed to add additional properties aside from the requested ones. We should support some.

To start with, we should support the `created_at` property like in the example.

**Comment by N0v0cain3** [comment]
Hey,

Wanted to get more context on the issue. Do you want to manually add a timestamp key `created_at` to the `ns.Properties` while creating a namespace?  https://github.com/Bodo-inc/denali/blob/c1e35316379626ec68e236df845ac91e08e8e5e6/logic/ns.go#L103

**Comment by srilman** [comment]
Yep exactly! And include a check in case `NamespaceContent.Properties` already contains `created_at` to avoid overwriting it.

**Comment by srilman** [comment]
@N0v0cain3 were you interested in working on it?

**Comment by N0v0cain3** [comment]
Seems like a good issue to start contributing to the project. I would love to give it a go!

**Comment by srilman** [comment]
Awesome, feel free to let us know if you run into any issues
